# Generated by Django 6.1.1 on 2026-10-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_person_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
